services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/php/Dockerfile
    container_name: laravel_11_livewire_adminlte_docker_app_new
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ../docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx_laravel_livewire_adminlte_docker_new
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_laravel_livewire_adminlte_docker_new
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_laravel_livewire_adminlte_docker_new
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
